[package]
name = "warden-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "warden"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap = { version = "4", features = ["derive"] }
dirs.workspace = true
serde.workspace = true
tokio.workspace = true
toml.workspace = true
warden-core = { path = "../warden-core" }
