[package]
name = "warden-server"
version.workspace = true
edition.workspace = true

[[bin]]
name = "warden-server"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
clap = { version = "4", features = ["derive"] }
dirs.workspace = true
futures-util = "0.3"
serde_json.workspace = true
tokio = { workspace = true, features = ["sync"] }
tokio-tungstenite = "0.30"
warden-bootstrap = { path = "../warden-bootstrap" }
warden-core = { path = "../warden-core" }
warden-server-protocol = { path = "../warden-server-protocol" }

[dev-dependencies]
base64.workspace = true
