// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `rt`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Sweeps the local network for `warden-server` hubs listening on `port` — same mechanism as
/// `desktop/src-tauri/src/workspace_cmds.rs::discover_hubs`. Never needs or reveals the auth key;
/// the `ConnectionScreen` still asks for that by hand, same security boundary as the desktop.
Future<List<DiscoveredHubDto>> bridgeDiscoverHubs({required int port}) =>
    RustLib.instance.api.crateApiDiscoveryBridgeDiscoverHubs(port: port);

class DiscoveredHubDto {
  final String host;
  final int port;
  final String serverName;

  /// Set when the hub only accepts `wss://` (P36) — where to connect instead of `ws://host:port`.
  final String? secureUrl;

  const DiscoveredHubDto({
    required this.host,
    required this.port,
    required this.serverName,
    this.secureUrl,
  });

  @override
  int get hashCode =>
      host.hashCode ^ port.hashCode ^ serverName.hashCode ^ secureUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is DiscoveredHubDto &&
          runtimeType == other.runtimeType &&
          host == other.host &&
          port == other.port &&
          serverName == other.serverName &&
          secureUrl == other.secureUrl;
}
