// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Toolchain smoke test (Fase 4.4, Estágio A) — proves the Android-compiled `.so` links and runs
/// inside the Flutter app before any real sync logic is wired in. Superseded by the real
/// `SyncEngine` bridge functions in Estágio B; kept as a cheap sanity check even after that lands.
String ping() => RustLib.instance.api.crateApiSimplePing();
