// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `store`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`

Future<List<SkillDto>> bridgeListSkills({required String vaultRoot}) =>
    RustLib.instance.api.crateApiSkillsBridgeListSkills(vaultRoot: vaultRoot);

/// `overwrite: false` is "create" (refuses a name already taken, so the New form can't silently
/// replace another skill); `true` is "edit" (the Dart side locks the name field then). Same
/// contract as the desktop's `save_skill`.
Future<void> bridgeSaveSkill({
  required String vaultRoot,
  required SkillDto skill,
  required bool overwrite,
}) => RustLib.instance.api.crateApiSkillsBridgeSaveSkill(
  vaultRoot: vaultRoot,
  skill: skill,
  overwrite: overwrite,
);

Future<void> bridgeDeleteSkill({
  required String vaultRoot,
  required String name,
}) => RustLib.instance.api.crateApiSkillsBridgeDeleteSkill(
  vaultRoot: vaultRoot,
  name: name,
);

class SkillDto {
  final String name;
  final String description;
  final String body;

  const SkillDto({
    required this.name,
    required this.description,
    required this.body,
  });

  @override
  int get hashCode => name.hashCode ^ description.hashCode ^ body.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SkillDto &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          description == other.description &&
          body == other.body;
}
