// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `engine`, `parse_hosts`, `rt`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`, `from`

SyncStatusDto bridgeStatus({
  required String vaultRoot,
  required String configPath,
  required String secretsPath,
  required String manifestPath,
}) => RustLib.instance.api.crateApiSyncBridgeStatus(
  vaultRoot: vaultRoot,
  configPath: configPath,
  secretsPath: secretsPath,
  manifestPath: manifestPath,
);

/// Generates a fresh vault key on this device. Rarely the mobile flow in practice — the phone
/// usually joins a group a desktop/CLI already started (`bridge_pairing_join`) — but kept for
/// symmetry: nothing stops the phone from being the first device.
Future<void> bridgeInitFresh({
  required String vaultRoot,
  required String configPath,
  required String secretsPath,
  required String manifestPath,
}) => RustLib.instance.api.crateApiSyncBridgeInitFresh(
  vaultRoot: vaultRoot,
  configPath: configPath,
  secretsPath: secretsPath,
  manifestPath: manifestPath,
);

/// Step 1 of Send: computes the diff, encrypts the bundle, and stashes it in `PENDING_PUSH` for
/// `bridge_push_await` to pick up — `qr_payload_json` is rendered into an actual QR image on the
/// Dart side via `qr_flutter`, for the separate TruthID app to scan.
Future<PushBeginDto?> bridgePushBegin({
  required String vaultRoot,
  required String configPath,
  required String secretsPath,
  required String manifestPath,
}) => RustLib.instance.api.crateApiSyncBridgePushBegin(
  vaultRoot: vaultRoot,
  configPath: configPath,
  secretsPath: secretsPath,
  manifestPath: manifestPath,
);

/// Step 2 of Send: waits for the TruthID phone to pin the bundle prepared by `bridge_push_begin`,
/// then persists the updated manifest at `manifest_path`.
Future<PushResultDto> bridgePushAwait({
  required String manifestPath,
  required List<String> hosts,
}) => RustLib.instance.api.crateApiSyncBridgePushAwait(
  manifestPath: manifestPath,
  hosts: hosts,
);

Future<PullResultDto> bridgePull({
  required String vaultRoot,
  required String configPath,
  required String secretsPath,
  required String manifestPath,
}) => RustLib.instance.api.crateApiSyncBridgePull(
  vaultRoot: vaultRoot,
  configPath: configPath,
  secretsPath: secretsPath,
  manifestPath: manifestPath,
);

/// Starts showing a pairing code and stashes the listener in `PENDING_PAIRING_HOST` — call
/// `bridge_pairing_host_wait` right after to block (in a Dart `Future`, not the UI thread) until
/// another device joins or the 5-minute window (`PAIRING_TIMEOUT`) lapses.
Future<String> bridgePairingHostStart({
  required String vaultRoot,
  required String configPath,
  required String secretsPath,
  required String manifestPath,
}) => RustLib.instance.api.crateApiSyncBridgePairingHostStart(
  vaultRoot: vaultRoot,
  configPath: configPath,
  secretsPath: secretsPath,
  manifestPath: manifestPath,
);

Future<void> bridgePairingHostWait() =>
    RustLib.instance.api.crateApiSyncBridgePairingHostWait();

/// Sweeps for a device showing `code` and adopts the vault key it hands over. The usual mobile
/// path — the phone typically joins a group a desktop/CLI already started.
Future<void> bridgePairingJoin({
  required String vaultRoot,
  required String configPath,
  required String secretsPath,
  required String manifestPath,
  required String code,
  required List<String> hosts,
}) => RustLib.instance.api.crateApiSyncBridgePairingJoin(
  vaultRoot: vaultRoot,
  configPath: configPath,
  secretsPath: secretsPath,
  manifestPath: manifestPath,
  code: code,
  hosts: hosts,
);

class PullResultDto {
  final String? txId;
  final int filesWritten;
  final int filesDeleted;
  final bool configUpdated;
  final List<String> warnings;

  const PullResultDto({
    this.txId,
    required this.filesWritten,
    required this.filesDeleted,
    required this.configUpdated,
    required this.warnings,
  });

  @override
  int get hashCode =>
      txId.hashCode ^
      filesWritten.hashCode ^
      filesDeleted.hashCode ^
      configUpdated.hashCode ^
      warnings.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PullResultDto &&
          runtimeType == other.runtimeType &&
          txId == other.txId &&
          filesWritten == other.filesWritten &&
          filesDeleted == other.filesDeleted &&
          configUpdated == other.configUpdated &&
          warnings == other.warnings;
}

class PushBeginDto {
  final String qrPayloadJson;
  final int filesChanged;
  final bool configChanged;

  const PushBeginDto({
    required this.qrPayloadJson,
    required this.filesChanged,
    required this.configChanged,
  });

  @override
  int get hashCode =>
      qrPayloadJson.hashCode ^ filesChanged.hashCode ^ configChanged.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PushBeginDto &&
          runtimeType == other.runtimeType &&
          qrPayloadJson == other.qrPayloadJson &&
          filesChanged == other.filesChanged &&
          configChanged == other.configChanged;
}

class PushResultDto {
  final String txId;
  final int filesChanged;
  final bool configChanged;

  const PushResultDto({
    required this.txId,
    required this.filesChanged,
    required this.configChanged,
  });

  @override
  int get hashCode =>
      txId.hashCode ^ filesChanged.hashCode ^ configChanged.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PushResultDto &&
          runtimeType == other.runtimeType &&
          txId == other.txId &&
          filesChanged == other.filesChanged &&
          configChanged == other.configChanged;
}

class SyncStatusDto {
  final bool paired;
  final String? deviceId;
  final String? ownerAddress;
  final String? lastTxId;
  final PlatformInt64? lastSyncedAtMs;
  final int pendingVaultChanges;
  final bool pendingConfigChanged;

  const SyncStatusDto({
    required this.paired,
    this.deviceId,
    this.ownerAddress,
    this.lastTxId,
    this.lastSyncedAtMs,
    required this.pendingVaultChanges,
    required this.pendingConfigChanged,
  });

  @override
  int get hashCode =>
      paired.hashCode ^
      deviceId.hashCode ^
      ownerAddress.hashCode ^
      lastTxId.hashCode ^
      lastSyncedAtMs.hashCode ^
      pendingVaultChanges.hashCode ^
      pendingConfigChanged.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncStatusDto &&
          runtimeType == other.runtimeType &&
          paired == other.paired &&
          deviceId == other.deviceId &&
          ownerAddress == other.ownerAddress &&
          lastTxId == other.lastTxId &&
          lastSyncedAtMs == other.lastSyncedAtMs &&
          pendingVaultChanges == other.pendingVaultChanges &&
          pendingConfigChanged == other.pendingConfigChanged;
}
