// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/simple.dart';
import 'api/sync.dart';

import 'dart:async';
import 'dart:convert';

import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.13.0';

  @override
  int get rustContentHash => -1941701642;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'warden_mobile_bridge',
        ioDirectory: '../crates/warden-mobile-bridge/target/release/',
        webPrefix: 'pkg/',
        wasmBindgenName: 'wasm_bindgen',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateApiSyncBridgeInitFresh({
    required String vaultRoot,
    required String configPath,
    required String secretsPath,
    required String manifestPath,
  });

  Future<String> crateApiSyncBridgePairingHostStart({
    required String vaultRoot,
    required String configPath,
    required String secretsPath,
    required String manifestPath,
  });

  Future<void> crateApiSyncBridgePairingHostWait();

  Future<void> crateApiSyncBridgePairingJoin({
    required String vaultRoot,
    required String configPath,
    required String secretsPath,
    required String manifestPath,
    required String code,
    required List<String> hosts,
  });

  Future<PullResultDto> crateApiSyncBridgePull({
    required String vaultRoot,
    required String configPath,
    required String secretsPath,
    required String manifestPath,
  });

  Future<PushResultDto> crateApiSyncBridgePushAwait({
    required String manifestPath,
    required List<String> hosts,
  });

  Future<PushBeginDto?> crateApiSyncBridgePushBegin({
    required String vaultRoot,
    required String configPath,
    required String secretsPath,
    required String manifestPath,
  });

  SyncStatusDto crateApiSyncBridgeStatus({
    required String vaultRoot,
    required String configPath,
    required String secretsPath,
    required String manifestPath,
  });

  Future<void> crateApiSimpleInitApp();

  String crateApiSimplePing();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateApiSyncBridgeInitFresh({
    required String vaultRoot,
    required String configPath,
    required String secretsPath,
    required String manifestPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(vaultRoot, serializer);
          sse_encode_String(configPath, serializer);
          sse_encode_String(secretsPath, serializer);
          sse_encode_String(manifestPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSyncBridgeInitFreshConstMeta,
        argValues: [vaultRoot, configPath, secretsPath, manifestPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSyncBridgeInitFreshConstMeta =>
      const TaskConstMeta(
        debugName: "bridge_init_fresh",
        argNames: ["vaultRoot", "configPath", "secretsPath", "manifestPath"],
      );

  @override
  Future<String> crateApiSyncBridgePairingHostStart({
    required String vaultRoot,
    required String configPath,
    required String secretsPath,
    required String manifestPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(vaultRoot, serializer);
          sse_encode_String(configPath, serializer);
          sse_encode_String(secretsPath, serializer);
          sse_encode_String(manifestPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSyncBridgePairingHostStartConstMeta,
        argValues: [vaultRoot, configPath, secretsPath, manifestPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSyncBridgePairingHostStartConstMeta =>
      const TaskConstMeta(
        debugName: "bridge_pairing_host_start",
        argNames: ["vaultRoot", "configPath", "secretsPath", "manifestPath"],
      );

  @override
  Future<void> crateApiSyncBridgePairingHostWait() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSyncBridgePairingHostWaitConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSyncBridgePairingHostWaitConstMeta =>
      const TaskConstMeta(debugName: "bridge_pairing_host_wait", argNames: []);

  @override
  Future<void> crateApiSyncBridgePairingJoin({
    required String vaultRoot,
    required String configPath,
    required String secretsPath,
    required String manifestPath,
    required String code,
    required List<String> hosts,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(vaultRoot, serializer);
          sse_encode_String(configPath, serializer);
          sse_encode_String(secretsPath, serializer);
          sse_encode_String(manifestPath, serializer);
          sse_encode_String(code, serializer);
          sse_encode_list_String(hosts, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSyncBridgePairingJoinConstMeta,
        argValues: [
          vaultRoot,
          configPath,
          secretsPath,
          manifestPath,
          code,
          hosts,
        ],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSyncBridgePairingJoinConstMeta =>
      const TaskConstMeta(
        debugName: "bridge_pairing_join",
        argNames: [
          "vaultRoot",
          "configPath",
          "secretsPath",
          "manifestPath",
          "code",
          "hosts",
        ],
      );

  @override
  Future<PullResultDto> crateApiSyncBridgePull({
    required String vaultRoot,
    required String configPath,
    required String secretsPath,
    required String manifestPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(vaultRoot, serializer);
          sse_encode_String(configPath, serializer);
          sse_encode_String(secretsPath, serializer);
          sse_encode_String(manifestPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_pull_result_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSyncBridgePullConstMeta,
        argValues: [vaultRoot, configPath, secretsPath, manifestPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSyncBridgePullConstMeta => const TaskConstMeta(
    debugName: "bridge_pull",
    argNames: ["vaultRoot", "configPath", "secretsPath", "manifestPath"],
  );

  @override
  Future<PushResultDto> crateApiSyncBridgePushAwait({
    required String manifestPath,
    required List<String> hosts,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(manifestPath, serializer);
          sse_encode_list_String(hosts, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_push_result_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSyncBridgePushAwaitConstMeta,
        argValues: [manifestPath, hosts],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSyncBridgePushAwaitConstMeta =>
      const TaskConstMeta(
        debugName: "bridge_push_await",
        argNames: ["manifestPath", "hosts"],
      );

  @override
  Future<PushBeginDto?> crateApiSyncBridgePushBegin({
    required String vaultRoot,
    required String configPath,
    required String secretsPath,
    required String manifestPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(vaultRoot, serializer);
          sse_encode_String(configPath, serializer);
          sse_encode_String(secretsPath, serializer);
          sse_encode_String(manifestPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_opt_box_autoadd_push_begin_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSyncBridgePushBeginConstMeta,
        argValues: [vaultRoot, configPath, secretsPath, manifestPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSyncBridgePushBeginConstMeta =>
      const TaskConstMeta(
        debugName: "bridge_push_begin",
        argNames: ["vaultRoot", "configPath", "secretsPath", "manifestPath"],
      );

  @override
  SyncStatusDto crateApiSyncBridgeStatus({
    required String vaultRoot,
    required String configPath,
    required String secretsPath,
    required String manifestPath,
  }) {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(vaultRoot, serializer);
          sse_encode_String(configPath, serializer);
          sse_encode_String(secretsPath, serializer);
          sse_encode_String(manifestPath, serializer);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_sync_status_dto,
          decodeErrorData: sse_decode_String,
        ),
        constMeta: kCrateApiSyncBridgeStatusConstMeta,
        argValues: [vaultRoot, configPath, secretsPath, manifestPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSyncBridgeStatusConstMeta => const TaskConstMeta(
    debugName: "bridge_status",
    argNames: ["vaultRoot", "configPath", "secretsPath", "manifestPath"],
  );

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimpleInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  String crateApiSimplePing() {
    return handler.executeSync(
      SyncTask(
        callFfi: () {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kCrateApiSimplePingConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kCrateApiSimplePingConstMeta =>
      const TaskConstMeta(debugName: "ping", argNames: []);

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  PushBeginDto dco_decode_box_autoadd_push_begin_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_push_begin_dto(raw);
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  PushBeginDto? dco_decode_opt_box_autoadd_push_begin_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_push_begin_dto(raw);
  }

  @protected
  PullResultDto dco_decode_pull_result_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return PullResultDto(
      txId: dco_decode_opt_String(arr[0]),
      filesWritten: dco_decode_u_32(arr[1]),
      filesDeleted: dco_decode_u_32(arr[2]),
      configUpdated: dco_decode_bool(arr[3]),
      warnings: dco_decode_list_String(arr[4]),
    );
  }

  @protected
  PushBeginDto dco_decode_push_begin_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return PushBeginDto(
      qrPayloadJson: dco_decode_String(arr[0]),
      filesChanged: dco_decode_u_32(arr[1]),
      configChanged: dco_decode_bool(arr[2]),
    );
  }

  @protected
  PushResultDto dco_decode_push_result_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return PushResultDto(
      txId: dco_decode_String(arr[0]),
      filesChanged: dco_decode_u_32(arr[1]),
      configChanged: dco_decode_bool(arr[2]),
    );
  }

  @protected
  SyncStatusDto dco_decode_sync_status_dto(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return SyncStatusDto(
      paired: dco_decode_bool(arr[0]),
      deviceId: dco_decode_opt_String(arr[1]),
      ownerAddress: dco_decode_opt_String(arr[2]),
      lastTxId: dco_decode_opt_String(arr[3]),
      lastSyncedAtMs: dco_decode_opt_box_autoadd_i_64(arr[4]),
      pendingVaultChanges: dco_decode_u_32(arr[5]),
      pendingConfigChanged: dco_decode_bool(arr[6]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  PushBeginDto sse_decode_box_autoadd_push_begin_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_push_begin_dto(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PushBeginDto? sse_decode_opt_box_autoadd_push_begin_dto(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_push_begin_dto(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PullResultDto sse_decode_pull_result_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_txId = sse_decode_opt_String(deserializer);
    var var_filesWritten = sse_decode_u_32(deserializer);
    var var_filesDeleted = sse_decode_u_32(deserializer);
    var var_configUpdated = sse_decode_bool(deserializer);
    var var_warnings = sse_decode_list_String(deserializer);
    return PullResultDto(
      txId: var_txId,
      filesWritten: var_filesWritten,
      filesDeleted: var_filesDeleted,
      configUpdated: var_configUpdated,
      warnings: var_warnings,
    );
  }

  @protected
  PushBeginDto sse_decode_push_begin_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_qrPayloadJson = sse_decode_String(deserializer);
    var var_filesChanged = sse_decode_u_32(deserializer);
    var var_configChanged = sse_decode_bool(deserializer);
    return PushBeginDto(
      qrPayloadJson: var_qrPayloadJson,
      filesChanged: var_filesChanged,
      configChanged: var_configChanged,
    );
  }

  @protected
  PushResultDto sse_decode_push_result_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_txId = sse_decode_String(deserializer);
    var var_filesChanged = sse_decode_u_32(deserializer);
    var var_configChanged = sse_decode_bool(deserializer);
    return PushResultDto(
      txId: var_txId,
      filesChanged: var_filesChanged,
      configChanged: var_configChanged,
    );
  }

  @protected
  SyncStatusDto sse_decode_sync_status_dto(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_paired = sse_decode_bool(deserializer);
    var var_deviceId = sse_decode_opt_String(deserializer);
    var var_ownerAddress = sse_decode_opt_String(deserializer);
    var var_lastTxId = sse_decode_opt_String(deserializer);
    var var_lastSyncedAtMs = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_pendingVaultChanges = sse_decode_u_32(deserializer);
    var var_pendingConfigChanged = sse_decode_bool(deserializer);
    return SyncStatusDto(
      paired: var_paired,
      deviceId: var_deviceId,
      ownerAddress: var_ownerAddress,
      lastTxId: var_lastTxId,
      lastSyncedAtMs: var_lastSyncedAtMs,
      pendingVaultChanges: var_pendingVaultChanges,
      pendingConfigChanged: var_pendingConfigChanged,
    );
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_i_64(
    PlatformInt64 self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_push_begin_dto(
    PushBeginDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_push_begin_dto(self, serializer);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(
    PlatformInt64? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_push_begin_dto(
    PushBeginDto? self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_push_begin_dto(self, serializer);
    }
  }

  @protected
  void sse_encode_pull_result_dto(
    PullResultDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.txId, serializer);
    sse_encode_u_32(self.filesWritten, serializer);
    sse_encode_u_32(self.filesDeleted, serializer);
    sse_encode_bool(self.configUpdated, serializer);
    sse_encode_list_String(self.warnings, serializer);
  }

  @protected
  void sse_encode_push_begin_dto(PushBeginDto self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.qrPayloadJson, serializer);
    sse_encode_u_32(self.filesChanged, serializer);
    sse_encode_bool(self.configChanged, serializer);
  }

  @protected
  void sse_encode_push_result_dto(
    PushResultDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.txId, serializer);
    sse_encode_u_32(self.filesChanged, serializer);
    sse_encode_bool(self.configChanged, serializer);
  }

  @protected
  void sse_encode_sync_status_dto(
    SyncStatusDto self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.paired, serializer);
    sse_encode_opt_String(self.deviceId, serializer);
    sse_encode_opt_String(self.ownerAddress, serializer);
    sse_encode_opt_String(self.lastTxId, serializer);
    sse_encode_opt_box_autoadd_i_64(self.lastSyncedAtMs, serializer);
    sse_encode_u_32(self.pendingVaultChanges, serializer);
    sse_encode_bool(self.pendingConfigChanged, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}
